import { BrokerPortal } from '@/hooks/useBrokerPortal';

export function buildDemoPortal(templateId: number): BrokerPortal {
  return {
    id: 'demo',
    user_id: 'demo',
    slug: `preview-${templateId}`,
    custom_domain: null,
    template_id: templateId,
    is_active: true,
    properties_source: 'OWN',
    city: 'Ribeirão Preto',
    state: 'SP',
    branding: {
      logo_url: '',
      primary_color: '#1c1c1c',
      accent_color: '#c9a44c',
      bg_color: '#1c1c1c',
      hero_bg_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80',
      hero_title: 'Encontre o imóvel dos seus sonhos',
      hero_subtitle: 'Os melhores imóveis selecionados para você',
      whatsapp: '5516999999999',
      phone: '(16) 99999-9999',
      email: 'contato@exemplo.com.br',
      instagram: 'https://instagram.com',
      facebook: 'https://facebook.com',
      address: 'Av. Exemplo, 1000 - Ribeirão Preto/SP',
      cnpj: '00.000.000/0001-00',
      creci: 'CRECI 00000-J',
      about_text: 'Imobiliária com mais de 20 anos de tradição em Ribeirão Preto. Oferecemos os melhores imóveis com atendimento personalizado e dedicado.',
      about_image_url: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800&q=80',
      footer_text: 'Imobiliária Demo — todos os direitos reservados',
    },
    seo: { title: 'Preview', description: '', favicon_url: '' },
  };
}

export function buildDemoProperties(): any[] {
  const photos = [
    'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
    'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
    'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80',
    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
    'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80',
    'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80',
    'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&q=80',
  ];
  const base = [
    { type: 'CASA', op: 'SALE', price: 1250000, neighborhood: 'Jardim Botânico', status: 'NOVO', area: 280, beds: 4, baths: 3, parking: 2 },
    { type: 'APARTAMENTO', op: 'SALE', price: 850000, neighborhood: 'Centro', status: 'USADO', area: 120, beds: 3, baths: 2, parking: 2 },
    { type: 'COBERTURA', op: 'SALE', price: 2100000, neighborhood: 'Alto da Boa Vista', status: 'NOVO', area: 320, beds: 4, baths: 4, parking: 3 },
    { type: 'CASA', op: 'RENT', price: 4500, neighborhood: 'Ribeirânia', status: 'USADO', area: 180, beds: 3, baths: 2, parking: 2 },
    { type: 'APARTAMENTO', op: 'RENT', price: 2800, neighborhood: 'Jardim Sumaré', status: 'USADO', area: 75, beds: 2, baths: 1, parking: 1 },
    { type: 'TERRENO', op: 'SALE', price: 450000, neighborhood: 'Bonfim Paulista', status: 'NA_PLANTA', area: 500, beds: 0, baths: 0, parking: 0 },
    { type: 'SOBRADO', op: 'SALE', price: 980000, neighborhood: 'Jardim Califórnia', status: 'USADO', area: 240, beds: 4, baths: 3, parking: 2 },
    { type: 'APARTAMENTO', op: 'SALE', price: 1450000, neighborhood: 'Jardim Iraja', status: 'EM_CONSTRUCAO', area: 145, beds: 3, baths: 3, parking: 2 },
  ];
  return base.map((b, i) => ({
    id: `demo-${i + 1}`,
    user_id: 'demo',
    title: `${b.type === 'APARTAMENTO' ? 'Apartamento' : b.type === 'CASA' ? 'Casa' : b.type === 'COBERTURA' ? 'Cobertura' : b.type === 'TERRENO' ? 'Terreno' : 'Sobrado'} no ${b.neighborhood}`,
    description: 'Imóvel de alto padrão com acabamentos premium, localização privilegiada e ótima infraestrutura. Excelente oportunidade.',
    reference_code: `REF${1000 + i}`,
    property_type: b.type,
    operation_type: b.op,
    status: b.status,
    price_sale: b.op === 'SALE' ? b.price : null,
    price_rent: b.op === 'RENT' ? b.price : null,
    condo_fee: b.type === 'APARTAMENTO' || b.type === 'COBERTURA' ? 850 : null,
    iptu: 350,
    area_total: b.area,
    area_useful: Math.round(b.area * 0.85),
    bedrooms: b.beds,
    suites: Math.max(0, b.beds - 2),
    bathrooms: b.baths,
    parking_spots: b.parking,
    city: 'Ribeirão Preto',
    state: 'SP',
    neighborhood: b.neighborhood,
    address: `Rua Exemplo, ${100 + i} - ${b.neighborhood}`,
    zip_code: '14000-000',
    latitude: -21.1775 + (Math.random() - 0.5) * 0.05,
    longitude: -47.8103 + (Math.random() - 0.5) * 0.05,
    is_active: true,
    photos: photos.slice((i * 2) % photos.length, ((i * 2) % photos.length) + 4).map((url, idx) => ({ url, order: idx, is_cover: idx === 0 })),
    amenities: {},
    features: {},
    created_at: new Date().toISOString(),
  }));
}
