project_id = "hmcpfedcvkurttyolurv"

[functions.create-payment]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.send-whatsapp-code]
verify_jwt = false

[functions.verify-whatsapp-code]
verify_jwt = false
